apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: applicationbib-azure-secrets
  namespace: applicationbib
spec:
  provider: azure

  secretObjects:
    - secretName: applicationbib-runtime-secrets
      type: Opaque
      data:
        - objectName: postgres-url
          key: POSTGRES_URL
        - objectName: postgres-username
          key: POSTGRES_USER
        - objectName: postgres-password
          key: POSTGRES_PASSWORD

  parameters:
    usePodIdentity: "false"
    clientID: "${AZ_WORKLOAD_CLIENT_ID}"
    keyvaultName: "${AZ_KEYVAULT_NAME}"
    tenantId: "${AZ_TENANT_ID}"
    cloudName: "AzurePublicCloud"

    objects: |
      array:
        - |
          objectName: firebase-service-account
          objectType: secret
          objectAlias: firebase.json
        - |
          objectName: postgres-url
          objectType: secret
        - |
          objectName: postgres-username
          objectType: secret
        - |
          objectName: postgres-password
          objectType: secret
