apiVersion: v1
kind: ServiceAccount
metadata:
  name: applicationbib-azure-sa
  namespace: applicationbib
  annotations:
    azure.workload.identity/client-id: "${AZ_WORKLOAD_CLIENT_ID}"
automountServiceAccountToken: true
