spring.application.name=ApplicationBib
server.port=8080

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

management.endpoints.web.exposure.include=health,mappings

spring.mvc.pathmatch.matching-strategy=ant-path-matcher
spring.mvc.view.prefix=/WEB-INF/view/
spring.mvc.view.suffix=.jsp


#connect db from vaul
spring.cloud.vault.uri=http://vault.vault.svc.cluster.local:8200
spring.cloud.vault.scheme=http
spring.cloud.vault.authentication=KUBERNETES
spring.cloud.vault.kubernetes.role=applicationbib
spring.cloud.vault.kubernetes.kubernetes-path=kubernetes
spring.cloud.vault.kv.enabled=true
spring.cloud.vault.kv.backend=secret
spring.cloud.vault.kv.backend-version=2
spring.config.import=optional:vault://secret/applicationbib/db
spring.datasource.url=${url}
spring.datasource.username=${username}
spring.datasource.password=${password}
