#connect db from vaul
spring.cloud.vault.uri=http://vault.vault.svc.cluster.local:8200
spring.cloud.vault.scheme=http
spring.cloud.vault.authentication=KUBERNETES
spring.cloud.vault.kubernetes.role=applicationbib
spring.cloud.vault.kubernetes.kubernetes-path=kubernetes
spring.cloud.vault.kv.enabled=true
spring.cloud.vault.kv.backend=secret
spring.cloud.vault.kv.backend-version=2
spring.config.import=optional:vault://secret/applicationbib/db

spring.datasource.url=${url}
spring.datasource.username=${username}
spring.datasource.password=${password}