apiVersion: apps/v1
kind: Deployment
metadata:
  name: applicationbib
spec:
  replicas: 1
  selector:
    matchLabels:
      app: applicationbib
  template:
    metadata:
      labels:
        app: applicationbib
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "applicationbib"

        vault.hashicorp.com/agent-inject-secret-firebase.json: "secret/data/applicationbib/firebase"

        vault.hashicorp.com/agent-inject-template-firebase.json: |
          {{- with secret "secret/data/applicationbib/firebase" -}}
          {{ index .Data.data "service-account.json" }}
          {{- end }}
    spec:
      serviceAccountName: applicationbib-sa
      imagePullSecrets:
        - name: gitlab-registry-secret

      containers:
        - name: applicationbib
          image: registry.gitlab.com/khalilmohamed798/applicationbib:a74f2d4a
          imagePullPolicy: Always
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "k8s"
            - name: FIREBASE_CREDENTIALS
              value: "/vault/secrets/firebase.json"
          ports:
            - containerPort: 8080

          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10

          resources:
            requests:
              cpu: "250m"
              memory: "384Mi"
              ephemeral-storage: "256Mi"
            limits:
              cpu: "1"
              memory: "768Mi"
              ephemeral-storage: "512Mi"

          securityContext:
            runAsNonRoot: true
            runAsUser: 10001
            runAsGroup: 10001
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL

          volumeMounts:
            - name: tmp
              mountPath: /tmp

      volumes:
        - name: tmp
          emptyDir: {}