apiVersion: apps/v1
kind: Deployment
metadata:
  name: ritual-growth-ui
  namespace: applicationbib
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ritual-growth-ui
  template:
    metadata:
      labels:
        app: ritual-growth-ui
    spec:
      containers:
        - name: ritual-growth-ui
          image: applicationbibacr.azurecr.io/ritual-growth-ui:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
              ephemeral-storage: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
              ephemeral-storage: "256Mi"
          securityContext:
            runAsNonRoot: true
            runAsUser: 10001
            runAsGroup: 10001
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          volumeMounts:
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: tmp
          emptyDir: {}
