apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: applicationbib
  namespace: applicationbib
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - <AZURE_APPLICATION_HOST>
      secretName: applicationbib-tls
  rules:
    - host: <AZURE_APPLICATION_HOST>
      http:
        paths:
          - path: /api(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: applicationbib
                port:
                  number: 8080
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ritual-growth-ui
                port:
                  number: 3000